# Generated by Django 3.2.9 on 2021-11-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0003_game_match_tournament")]

    operations = [
        migrations.RemoveField(model_name="match", name="name"),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["name"], name="app_agent_name_dfaacf_idx"),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["owner"], name="app_agent_owner_i_6c59b7_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["name"], name="app_game_name_573327_idx"),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["name"], name="app_tournam_name_8e0538_idx"),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["game"], name="app_tournam_game_id_abdd87_idx"),
        ),
    ]
