# Generated by Django 3.2.9 on 2021-11-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0004_auto_20211116_1233")]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
