# Generated by Django 3.2.9 on 2021-11-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0005_auto_20211116_1235")]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="files",
            field=models.FileField(null=True, upload_to=""),
        )
    ]
