# Generated by Django 3.2.9 on 2021-11-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0007_auto_20211116_1308")]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="file",
            field=models.FileField(null=True, upload_to=""),
        )
    ]
