# Generated by Django 3.2.9 on 2021-11-17 13:02

from django.db import migrations, models

import app.utils


class Migration(migrations.Migration):

    dependencies = [("app", "0008_agent_file")]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="file",
            field=models.FileField(null=True, upload_to=app.utils.agent_filepath),
        )
    ]
