# Generated by Django 3.2.9 on 2021-11-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0009_alter_agent_file")]

    operations = [
        migrations.RemoveField(model_name="tournament", name="matches"),
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.tournament",
            ),
        ),
    ]
