# Generated by Django 3.2.9 on 2021-11-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0010_auto_20211119_1137")]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="finished_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
    ]
