# Generated by Django 3.2.9 on 2021-11-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0011_auto_20211119_1139")]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="participants",
            field=models.ManyToManyField(related_name="matches", to="app.Agent"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="participants",
            field=models.ManyToManyField(related_name="tournaments", to="app.Agent"),
        ),
    ]
