# Generated by Django 3.2.9 on 2021-11-19 12:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0012_auto_20211119_1230")]

    operations = [
        migrations.CreateModel(
            name="AgentRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("wins", models.IntegerField(default=0)),
                ("loses", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "elo",
                    models.DecimalField(decimal_places=2, default=1500, max_digits=10),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.agent"
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
