# Generated by Django 3.2.9 on 2021-11-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0014_auto_20211119_1834")]

    operations = [
        migrations.AddField(
            model_name="match", name="data", field=models.JSONField(default=dict)
        ),
        migrations.AddField(
            model_name="match",
            name="result",
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=3),
        ),
    ]
