# Generated by Django 3.2.9 on 2021-11-19 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0015_auto_20211119_1908")]

    operations = [
        migrations.RemoveField(model_name="match", name="participants"),
        migrations.AddField(
            model_name="match",
            name="player1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="app.agent",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="app.agent",
            ),
        ),
    ]
