# Generated by Django 3.2.9 on 2021-11-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0016_auto_20211119_2335")]

    operations = [
        migrations.AddField(
            model_name="match",
            name="participants",
            field=models.ManyToManyField(related_name="matches", to="app.Agent"),
        )
    ]
