# Generated by Django 3.2.9 on 2021-11-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0018_auto_20211122_1152")]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="app.tournament",
            ),
        )
    ]
