# Generated by Django 3.2.9 on 2021-11-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0019_alter_match_tournament")]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="mode",
            field=models.CharField(
                choices=[
                    ("ROUND_ROBIN", "Round Robin"),
                    ("DOUBLE_ROUND_ROBIN", "Double Round Robin"),
                    ("TRIPLE_ROUND_ROBIN", "Triple Round Robin"),
                    ("TIMED", "Timed"),
                ],
                max_length=64,
            ),
        )
    ]
