# Generated by Django 3.2.9 on 2021-11-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0021_alter_match_ran_at")]

    operations = [
        migrations.AddField(
            model_name="agent", name="active", field=models.BooleanField(default=True)
        )
    ]
