# Generated by Django 3.2.9 on 2021-11-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("app", "0023_remove_agent_file_path")]

    operations = [
        migrations.RemoveField(model_name="tournament", name="finished_at"),
        migrations.RemoveField(model_name="tournament", name="started_at"),
    ]
