# Generated by Django 3.2.9 on 2021-11-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0026_tournament_automated")]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="automated",
            field=models.BooleanField(null=True),
        )
    ]
