# Generated by Django 3.2.9 on 2021-11-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0029_rename_automated_tournament_is_automated")]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="automated_number",
            field=models.IntegerField(null=True),
        )
    ]
