# Generated by Django 3.2.9 on 2021-11-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0031_agent_file_hash")]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="file_hash",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["elo"], name="app_agent_elo_ed7c1e_idx"),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["file_hash"], name="app_agent_file_ha_7f411b_idx"
            ),
        ),
    ]
