# Generated by Django 3.2.9 on 2021-11-26 12:59

from django.db import migrations


def delete_orphan_matches(apps, schema_editor):
    Match = apps.get_model("app", "Match")
    Match.objects.filter(tournament_id__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [("app", "0032_auto_20211125_1656")]

    operations = [migrations.RunPython(delete_orphan_matches)]
