# Generated by Django 3.2.9 on 2021-11-26 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0033_auto_20211126_1259")]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="app.tournament",
            ),
        )
    ]
