# Generated by Django 3.2.9 on 2021-11-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0035_match_errors")]

    operations = [
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["ran"], name="app_match_ran_3ed266_idx"),
        )
    ]
