# Generated by Django 3.2.9 on 2021-12-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0036_match_app_match_ran_3ed266_idx")]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="done",
            field=models.BooleanField(default=False, null=True),
        )
    ]
