# Generated by Django 3.2.9 on 2021-12-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0038_tournament_app_tournam_done_1831dc_idx")]

    operations = [
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["player1"], name="app_match_player1_597656_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["player2"], name="app_match_player2_b1eec5_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["tournament"], name="app_match_tournam_1f5c59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["is_automated"], name="app_tournam_is_auto_bb6512_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["mode"], name="app_tournam_mode_f52a42_idx"),
        ),
    ]
