# Generated by Django 3.2.9 on 2021-12-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0039_auto_20211207_1255")]

    operations = [
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["ran_at"], name="app_match_ran_at_7fe3d7_idx"),
        )
    ]
