# Generated by Django 3.2.9 on 2021-12-07 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0040_match_app_match_ran_at_7fe3d7_idx")]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="game",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.game"
            ),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["game"], name="app_agent_game_id_d49352_idx"),
        ),
    ]
