# Generated by Django 3.2.9 on 2021-12-07 23:28

from django.db import migrations


def populate_agent_game(apps, schema_editor):
    Agent = apps.get_model("app", "Agent")
    Game = apps.get_model("app", "Game")

    game = Game.objects.first()

    for agent in Agent.objects.all():
        agent.game = game
        agent.save(update_fields=["game"])


class Migration(migrations.Migration):
    dependencies = [("app", "0041_auto_20211207_2328")]

    operations = [migrations.RunPython(populate_agent_game)]
