# Generated by Django 3.2.9 on 2021-12-07 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0042_auto_20211207_2328")]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.game"
            ),
        )
    ]
