# Generated by Django 3.2.9 on 2021-12-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0044_match_app_match_ran_at_9c65ae_idx")]

    operations = [
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["id", "ran_at", "data"], name="app_match_id_1a352d_idx"
            ),
        )
    ]
