# Generated by Django 3.2.9 on 2021-12-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("app", "0045_match_app_match_id_1a352d_idx")]

    operations = [
        migrations.RemoveIndex(model_name="match", name="app_match_ran_at_9c65ae_idx"),
        migrations.RemoveIndex(model_name="match", name="app_match_id_1a352d_idx"),
    ]
