# Generated by Django 3.2.9 on 2021-12-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0046_auto_20211208_1300")]

    operations = [
        migrations.AddField(
            model_name="match",
            name="game",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.game"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["game"], name="app_match_game_id_eeab61_idx"),
        ),
    ]
