# Generated by Django 3.2.9 on 2021-12-10 11:53

from django.db import migrations


def populate_match_game(apps, schema_editor):
    Match = apps.get_model("app", "Match")
    Game = apps.get_model("app", "Game")

    game = Game.objects.first()

    for match in Match.objects.all().iterator():
        match.game = game
        match.save(update_fields=["game"])


class Migration(migrations.Migration):

    dependencies = [("app", "0047_auto_20211210_1153")]

    operations = [migrations.RunPython(populate_match_game)]
