# Generated by Django 3.2.9 on 2021-12-10 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0048_auto_20211210_1153")]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.game"
            ),
        )
    ]
