# Generated by Django 3.2.10 on 2021-12-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0049_alter_match_game")]

    operations = [
        migrations.AddField(
            model_name="game", name="active", field=models.BooleanField(default=True)
        )
    ]
