# Generated by Django 3.2.10 on 2021-12-24 16:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0050_game_active")]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(fields=["name"], name="app_season_name_a33d4e_idx"),
        ),
    ]
