# Generated by Django 3.2.10 on 2021-12-24 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0051_auto_20211224_1652")]

    operations = [
        migrations.AddField(
            model_name="match",
            name="season",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.season"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="season",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.season"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["season"], name="app_match_season__60a48b_idx"),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["season"], name="app_tournam_season__f9fd84_idx"
            ),
        ),
    ]
