# Generated by Django 3.2.10 on 2021-12-24 16:59

from django.db import migrations


def populate_match_season(apps, schema_editor):
    Match = apps.get_model("app", "Match")
    Season = apps.get_model("app", "Season")

    season = Season.objects.first()
    if season is None:
        raise ValueError("No season found!")

    while Match.objects.filter(season__isnull=True).exists():
        inner_q = Match.objects.filter(season__isnull=True)[0:10000]
        Match.objects.filter(pk__in=inner_q).update(season=season)


class Migration(migrations.Migration):
    dependencies = [("app", "0052_auto_20211224_1658")]

    operations = [migrations.RunPython(populate_match_season)]
