# Generated by Django 3.2.10 on 2021-12-24 17:15

from django.db import migrations


def populate_tournament_season(apps, schema_editor):
    Tournament = apps.get_model("app", "Tournament")
    Season = apps.get_model("app", "Season")

    season = Season.objects.first()
    if season is None:
        return

    while Tournament.objects.filter(season__isnull=True).exists():
        inner_q = Tournament.objects.filter(season__isnull=True)[0:10000]
        Tournament.objects.filter(pk__in=inner_q).update(season=season)


class Migration(migrations.Migration):
    dependencies = [("app", "0053_auto_20211224_1659")]

    operations = [migrations.RunPython(populate_tournament_season)]
