# Generated by Django 3.2.10 on 2021-12-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0054_auto_20211224_1715")]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.season"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.season"
            ),
        ),
    ]
