# Generated by Django 3.2.10 on 2021-12-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0055_auto_20211224_1717")]

    operations = [
        migrations.AddField(
            model_name="season", name="main", field=models.BooleanField(default=True)
        )
    ]
