# Generated by Django 3.2.10 on 2021-12-24 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0058_auto_20211224_1852")]

    operations = [
        migrations.AlterField(
            model_name="agentratings",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="app.agent",
            ),
        )
    ]
