# Generated by Django 3.2.10 on 2021-12-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0059_alter_agentratings_agent")]

    operations = [
        migrations.AlterUniqueTogether(
            name="agentratings", unique_together={("agent", "game", "season")}
        ),
        migrations.AddIndex(
            model_name="agentratings",
            index=models.Index(fields=["agent"], name="app_agentra_agent_i_217fc5_idx"),
        ),
        migrations.AddIndex(
            model_name="agentratings",
            index=models.Index(
                fields=["season"], name="app_agentra_season__ae6355_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentratings",
            index=models.Index(fields=["game"], name="app_agentra_game_id_fff4d4_idx"),
        ),
    ]
