# Generated by Django 3.2.10 on 2021-12-24 18:59

from django.db import migrations


def create_records(apps, schema_editor):
    Agent = apps.get_model("app", "Agent")
    AgentRatings = apps.get_model("app", "AgentRatings")
    Season = apps.get_model("app", "Season")

    if not Season.objects.filter(main=True, active=True).exists():
        return

    season = Season.objects.get(main=True, active=True)

    for agent in Agent.objects.all().iterator():
        if agent.ratings.filter(season=season).exists():
            print(
                f"agent '{agent.name}' '{agent.id}' already has ratings for '{season.name}'"
            )
        else:
            AgentRatings.objects.create(
                game=agent.game,
                season=season,
                agent=agent,
                wins=agent.wins,
                loses=agent.loses,
                draws=agent.draws,
                score=agent.score,
                elo=agent.elo,
            )


class Migration(migrations.Migration):
    dependencies = [("app", "0060_auto_20211224_1859")]

    operations = [migrations.RunPython(create_records, migrations.RunPython.noop)]
