# Generated by Django 3.2.10 on 2021-12-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("app", "0061_auto_20211224_1859")]

    operations = [
        migrations.RemoveIndex(model_name="agent", name="app_agent_elo_ed7c1e_idx"),
        migrations.RemoveField(model_name="agent", name="draws"),
        migrations.RemoveField(model_name="agent", name="elo"),
        migrations.RemoveField(model_name="agent", name="loses"),
        migrations.RemoveField(model_name="agent", name="score"),
        migrations.RemoveField(model_name="agent", name="wins"),
    ]
