# Generated by Django 3.2.10 on 2021-12-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0063_alter_agent_game")]

    operations = [
        migrations.AddField(
            model_name="season",
            name="automated_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="season",
            name="is_automated",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
