# Generated by Django 3.2.10 on 2021-12-26 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0064_auto_20211226_1629")]

    operations = [
        migrations.AlterField(
            model_name="agentratings",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="app.season",
            ),
        )
    ]
