# Generated by Django 3.2.10 on 2021-12-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0066_auto_20211226_2020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournaments",
                to="app.game",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournaments",
                to="app.season",
            ),
        ),
    ]
