# Generated by Django 3.2.10 on 2021-12-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0069_game_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="wiki_url",
            field=models.TextField(null=True),
        ),
    ]
