# Generated by Django 3.2.10 on 2021-12-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0070_game_wiki_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="durations",
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
