# Generated by Django 3.2.10 on 2021-12-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0071_match_durations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="durations",
            new_name="duration",
        ),
    ]
