# Generated by Django 3.2.10 on 2021-12-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0072_rename_durations_match_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="duration",
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
    ]
