# Generated by Django 3.2.10 on 2021-12-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0073_alter_match_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="duration",
            field=models.DecimalField(decimal_places=20, max_digits=25, null=True),
        ),
    ]
