# Generated by Django 3.2.10 on 2022-01-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_alter_match_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="end_reason",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
