# Generated by Django 3.2.10 on 2022-01-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0076_match_outcome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="end_reason",
            field=models.CharField(
                choices=[("RULES", "Rules"), ("TAINTED", "Tainted")],
                max_length=255,
                null=True,
            ),
        ),
    ]
