# Generated by Django 3.2.10 on 2022-01-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0077_alter_match_end_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="errors",
        ),
    ]
