# Generated by Django 3.2.13 on 2022-07-27 20:55

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0085_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
