name: Deploy

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ansible

    steps:
      - uses: actions/checkout@v2
        with:
          repository: "h3nnn4n/colosseum_infra"
          ref: production

      - name: Setup ssh
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Install requirements
        run: ansible-galaxy install -r requirements.yml

      - name: Deploy to webservers
        run: ansible-playbook -i environments/production  web_servers.yml
        env:
          VAULT_PASSWORD: "${{ secrets.VAULT_PASSWORD }}"

      - name: Deploy to celery workers
        run: ansible-playbook -i environments/production celery_workers.yml
        env:
          VAULT_PASSWORD: "${{ secrets.VAULT_PASSWORD }}"
