name: Unit Tests

on: [push]

env:
  DB_HOST: localhost

jobs:
  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 5s
          --health-retries 15

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 3s
          --health-timeout 5s
          --health-retries 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install poetry
        run: |
          python -m pip install poetry
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env

          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry config cache-dir .poetry
          poetry config virtualenvs.path .poetry/venv

      - name: Load poetry cache
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .poetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install project deps
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Collect static files
        run: |
          poetry run python manage.py collectstatic
        env:
          DJANGO_SETTINGS_MODULE: colosseum_website.settings.testing

      - name: Run pytest
        run: |
          poetry run pytest --verbose
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          REDIS_URL: redis://localhost:6379/5
          CELERY_REDIS_URL: redis://localhost:6379/6
          DJANGO_SETTINGS_MODULE: colosseum_website.settings.testing
